### ISSUE TITLE
It only works with older font-awesome version

### ISSUE THREAD

**Issue by iradovanovic** [hughjdavey/ngx-stars#2]
Hi. 
Im trying to use it in my project, but It works only with FA version 4.x.x. With the last one 5.x.x, where we have "fas/far" classes, for the icons, it won't work.

Maybe wouldn't be bad to have an option to define what classes we want to use.

**Comment by hughjdavey** [comment]
Hi @iradovanovic what happens when you try and use it? Can you post an error message?

ngx-stars should work with any FA version and even if there is no font awesome in the project, as it imports its own version of font awesome 4.

When you say define what classes you want to use, do you mean using other webfonts?

**Comment by iradovanovic** [comment]
Well, locally in my project it works, and now is clear from where (with cdn?) it comes FA v4.
But on the server, where we do SSR build, seems there it won't use own awesome v4, because there is available FA v5, and as you know, v5 is using different class syntax. There is no error, simple, the empty star, and the half star is not shown.

**Comment by hughjdavey** [comment]
Yes the FA v4 in ngx-stars comes from a CDN via a <link> tag in ngx-stars.component.html

So for some reason it is not working on your server - perhaps as it is unable to make the web request to the CDN? Either way you make a good point - ngx-stars should be able to work offline so maybe the solution is to bundle its own version of FA v4 inside instead of downloading it from CDN? And maybe I should add an option for people like you who want to use a different version of FA? What do you think?

**Comment by hughjdavey** [comment]
Or maybe there's no need to bundle font awesome because all we really need is 3 icons - the full star, the half star and the empty star. I will check the license of font awesome to see if this is possible but I think it will be. Then it would be much lighter-weight to just include the 3 icons as SVGs or something

**Comment by iradovanovic** [comment]
How would be about to define (to have the possibility to define) your own classes for a full star, empty and a half?

Or, include 3 svg icons, as you suggested...

**Comment by hughjdavey** [comment]
That sounds good. I could include 3 SVG icons to use by default, and also allow the user to define their own custom classes in which case we use their icons. If it sounds ok I can get started?

**Comment by iradovanovic** [comment]
Sounds good. Thank you.

**Comment by hughjdavey** [comment]
Great I should be able to do it over the weekend :+1:

**Comment by hughjdavey** [comment]
Hey @iradovanovic I have just published `ngx-stars` version `1.4.3` which should resolve your issues.

It has removed all font awesome dependencies and now uses font awesome 5 icons by default (SVGs bundled in library). It also adds a new option `customStarIcons` which allows using any other SVGs you like. You can see a demo at https://hughjdavey.github.io/ngx-stars (look for the `Customize icons` section).

Let me know if the new version works for you :)

**Comment by iradovanovic** [comment]
Thank you. I have already tried and looks good.
Now, I will close this issue.
Thank you again for your support.
